### ISSUE TITLE
Android versionCode bumped to semver?

### ISSUE THREAD

**Issue by RWOverdijk** [expo-community/standard-version-expo#10]
### Description of the bug

> standard-version --dry-run

✔ bumping version in package.json from 1.0.0 to 1.1.0
✔ bumping version in app.json from 1.0.0 to 1.1.0
✔ bumping version in app.json from 1.0.2 to 1.1.0
**✔ bumping version in app.json from 3 to 1.1.0**
✔ created CHANGELOG.md
✔ outputting changes to CHANGELOG.md

Shouldn't this go from 3 to 4?

### To Reproduce

https://dev.to/bycedric/simplify-expo-releases-with-standard-version-2f4o

#### Expected behavior

For it to go from 3 to 4

#### Actual behavior

It went from 3 to 1.1.0

### Additional context

I know issue is quite empty but... I tried 😅

**Comment by byCedric** [comment]
What's your version config? For each version "property" you have to specify the correct version bumper. Does it look something like this?

```
module.exports = {
  bumpFiles: [
    {
      filename: 'package.json',
    },
    {
      filename: 'app.json',
      updater: require.resolve('standard-version-expo'),
    },
    {
      filename: 'app.json',
      updater: require.resolve('standard-version-expo/android/increment'),
    },
    {
      filename: 'app.json',
      updater: require.resolve('standard-version-expo/ios'),
    },
  ],
};
```

(note the `android/increment`)

**Comment by RWOverdijk** [comment]
@byCedric aHA! I didn't get that from the dev link I added 😄 

_"Tries"_

But even then, same output.

```js
module.exports = {
  bumpFiles: [
    {
      filename: 'package.json',
    },
    {
      filename: 'app.json',
      updater: require.resolve('standard-version-expo'),
    },
    {
      filename: 'app.json',
      updater: require.resolve('standard-version-expo/ios'),
    },
    {
      filename: 'app.json',
      updater: require.resolve('standard-version-expo/android/increment'),
    },
  ],
};
```

Gives me:

> standard-version --dry-run "--release-as" "prepatch"

✔ bumping version in package.json from 1.0.0 to 1.0.1-0
✔ bumping version in app.json from 1.0.0 to 1.0.1-0
✔ bumping version in app.json from 3 to 1.0.1-0
✔ bumping version in app.json from 1.0.2 to 1.0.1-0
✔ created CHANGELOG.md
✔ outputting changes to CHANGELOG.md

**Comment by byCedric** [comment]
Hmm, that's weird. Could you try a dry-run with the `minor` type? Something could be up with the prepatch calculation.

**Comment by RWOverdijk** [comment]
@byCedric Same thing. And now I've disabled everything besides the increment for test:

```js
module.exports = {
  bumpFiles: [
    {
      filename: 'app.json',
      updater: require.resolve('standard-version-expo/android/increment'),
    }
  ],
};
```

Gives me:

> standard-version --dry-run "--release-as" "minor"

✔ bumping version in app.json from 3 to 1.1.0
✔ created CHANGELOG.md
✔ outputting changes to CHANGELOG.md

**Comment by RWOverdijk** [comment]
Maybe relevant, but I'm using these versions:

```
    "standard-version": "^7.1.0",
    "standard-version-expo": "^1.0.3"
```

**Comment by byCedric** [comment]
Ah, I think this a "cosmetic" issue only. Standard version uses the semver, not the actual value that was changed, in the logs. That means it's bumping your version with `+1` when you use the `android/increment` bumper, but [the output is the semver from `package.json`](https://github.com/conventional-changelog/standard-version/blob/2f04ac8fc1c134a1981c23a093d4eece77d0bbb9/lib/lifecycles/bump.js#L163). This should be fixed anyway 😄

**Comment by RWOverdijk** [comment]
That is absolutely correct! It works :) Thanks! 🎉 

Maybe update the DEV post as well with the /increment thing for android (I shared it with some people and they'll probably have the same issue).

Again, thanks for this.

**Comment by byCedric** [comment]
Thanks for the tip, I'll add it!

**Comment by RWOverdijk** [comment]
@byCedric Hey, it's me again. 😄 

Prereleases do mess up the ios buildNumber a tad:

"buildNumber": "1.1.0-0",

Is this also a config issue?

**Comment by byCedric** [comment]
Hmm, thanks for catching that one. I'll investigate this a bit further on Wednesday!
