### ISSUE TITLE
Get sdkVersion from expo package.json

### ISSUE THREAD

**Issue by awinograd** [expo-community/standard-version-expo#7]
### Description of the bug

Expo has deprecated putting sdkVersion in `app.json` in favor of using the version defined by `node_modules/expo/package.json`'s `version` field. Would be great if this plugin started using that as the source as well.

### To Reproduce

1. Remove sdkVersion from app.json (automatically done by `expo upgrade`)
2. run standard-releasse

#### Expected behavior

properly detects sdkVersion

#### Actual behavior

doesnt bump android version because of missing sdkVersion in app.json

**Comment by byCedric** [comment]
Hi @awinograd, I'm so sorry for my late reply! You are right, I'll update that part to use the new config packages. Thanks for brining it up ❤️

**Comment by awinograd** [comment]
No worries at all! Thanks for the library and congrats on your new position w/Expo!

**Comment by byCedric** [comment]
Done! Version `1.0.3` should do the trick 😄 Thanks, hope to see you on the repos there!
